version: 2

references:
  default_machine_job: &default_machine_job
    machine: true
    working_directory: ~/workdir

jobs:
  checkout_and_test:
    <<: *default_machine_job
    steps:
      - checkout
      - run:
          name: Run report and test
          command: |
            mvn jacoco:report
            wget https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar -O codacy-coverage-reporter-assembly.jar
            java -cp codacy-coverage-reporter-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir

workflows:
  version: 2
  test:
    jobs:
      - checkout_and_test
